### ISSUE TITLE
Misplaced top silkscreen layer

### ISSUE THREAD

**Issue by skabashnyuk** [nasys/badgerboard#12]
<img width="1440" alt="2017-09-30 20 25 28" src="https://user-images.githubusercontent.com/1614429/31048031-d680b69a-a61d-11e7-8672-a93ab089f7b4.png">

**Comment by skabashnyuk** [comment]
Any comments? Is this expected or it's just mine local problem?

**Comment by KertIlm** [comment]
Hello,
This is not your problem since silkscreen is not used by Nordic Automation Systems. Due to that reason they don't pay attention to this layer. The components are tiny and side-by-side thus it makes no sense to label them on PCB especially when design files are public so everyone can just check them from there.
