### ISSUE TITLE
hc-sr04

### ISSUE THREAD

**Issue by qvs5010** [nasys/badgerboard#15]
Hi 

is it posible to to use the hc-sr04 sensor with the badgerboard?

Thanks

**Comment by KertIlm** [comment]
Hi qvs5010,

Short answer is YES. If you can find an Arduino guide like [this](https://howtomechatronics.com/tutorials/arduino/ultrasonic-sensor-hc-sr04/) then you most likely can also build it on badgerboard ... just make sure you have the correct pins from [here](http://badgerboard.io/wp-content/uploads/2017/02/badgerboard_pinout.pdf).
Biggest exception is that you can't use hardware uart because it is connected directly to RN2483(2903) module.

**Comment by qvs5010** [comment]
Hi Kertllm

Thanks

I have found the Badgerboard  //drowning sensor example where you use the following pins

void setup() 
```
{
    pinMode(A0,OUTPUT);  // Physical pi A0 on the board ?
    pinMode(A1,INPUT);
    digitalWrite(A0,LOW); // Pin A0 |   LOW is off / HIGH is on ?
    digitalWrite(A1,LOW); // Pin A1
.......
```
So I can use Boardpin A0 for TrigPin (Output) and then Boardpin A1 for EchoPin (Input)

```
long duration;
int distance;

bool testDist() //read analog value of sensor
{
    digitalWrite(A0,HIGH);
    delayMicroseconds(10);
    digitalWrite(A0,LOW);

    duration = pulseIn(digitalWrite(A1,HIGH));
    distance= duration*0.034/2;

    Serial.println(distance);
    return distance;

}

```
Sensor      BadgerBoard
Ground -   Ground Pin
VCC -         3.3V Pin
Trig -          A0 Pin
Echo -        A1 Pin


Also the Badgerboard is 3.3v and the Sensor in 3.3 to5v, but the echo is 5v only,  so it would be wise to put a resistor? :P 

```
Dejan Nedelkovski December 29, 2015 
The problem might be that you are using Arduino DUE, which has 3.3V pins and the ultrasonic sensors is working with 5V. Try using an resistor at the echo pin, as the 3.3V are fine for the Trig pin, but the Echo pin of the sensor will output 5V to your Arduino DUI which might damage it.
```

**Comment by qvs5010** [comment]
Hi 

I having some issues getting the badger board to talk to the sensor.

I tried all the ports, but no. luck.

What 2 pins can i use on the board for this sensor?

http://badgerboard.io/wp-content/uploads/2017/02/badgerboard_pinout.pdf

**Comment by qvs5010** [comment]
Hi 

this is the code i'm using, i removed all the lora code for now, just to get the sensor going.

```
// defines pins numbers
const int trigPin = 9;
const int echoPin = 10;
// defines variables
long duration;
int distance;
    
void setup() 
{

    pinMode(trigPin, OUTPUT); // Sets the trigPin as an Output
    pinMode(echoPin, INPUT); // Sets the echoPin as an Input
    
    //badger_init();
    //Serial.println("badger temp/hum sensor");
    //badger_print_EUI(devEUI);
    //LoRa_init(devEUI, appEUI, appKey,true);
    
}



void loop()
{
    badger_pulse_led(1);
    // Clears the trigPin
    digitalWrite(trigPin, LOW);
    delayMicroseconds(2);
    // Sets the trigPin on HIGH state for 10 micro seconds
    digitalWrite(trigPin, HIGH);
    delayMicroseconds(10);
    digitalWrite(trigPin, LOW);
    // Reads the echoPin, returns the sound wave travel time in microseconds
    duration = pulseIn(echoPin, HIGH);
    Serial.println(duration);
    // Calculating the distance
    distance = duration*0.034/2;
    // Prints the distance on the Serial Monitor
    Serial.print("Distance: ");
    Serial.println(distance);

    //if(temp_sched.run_now())
    //{
        // this function is called when the time defined at the "temp_sched" variable is reached
        //badger_pulse_led(1);
        
        //badger_blink_error(badger_temp_sensor_send());
    //}
    //temp_sched.print_soonest();
    if(Lora_requires_reset())
    {
        badger_restart();        
    }
    //badger_sleep_now(s_badger_sleep_period_ms);
}
```
On the Console my echo pin only read 4 regardless how far the sensor is, if i unplug the echo port i get 0,

I think i have the right pins.

**Comment by KertIlm** [comment]
Hi,

I tested it out myself and i got same results as you. I looked at the sensor and saw [that is a 3-5.5 vdc](https://www.geekbuying.com/item/HC-SR04-Ultrasonic-Sensor-Distance-Measuring-Module-3-3V---5V-Compatible-for-Arduino-NodeMCU-360876.html) sensor. I tested it out but it did not work with 3.3 vdc. If you power badgerboard via USB then you can use Vin pin to get ~5 vdc out from there... since echo pin outputs 5 vdc you have to build a voltage divider from echo pin to badgerboard([divide 5 volts to 3.3](http://www.ohmslawcalculator.com/voltage-divider-calculator)).

**Comment by qvs5010** [comment]
Hi K

Thanks for the reply

I figure I need the devider, lol.
I just need to get the resistors this week then will do another test.

![level shifter](https://user-images.githubusercontent.com/491550/39750033-7c3d7454-52b4-11e8-9159-364aa632b201.jpeg)

**Comment by qvs5010** [comment]
Hi K

I got some resistors and all is working now, Thanks!!

Was a major learning curve on giop's lol.
